# Site settings
title: Testing a template
description: > Testing a Start Bootstrap Jekyll theme. What do I want, pure html or do
              I like to have pages generated based on data? # this means to ignore newlines until "baseurl:"
baseurl: "/testhtml/" # the subpath of your site, e.g. /blog/
url: "https://wijnandb.github.io" # the base hostname & protocol for your site
author: Copyright &copy; 2023 - Start Bootstrap
lang: en_US

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
